### ISSUE TITLE
Implement password reminder functionality

### ISSUE THREAD

**Issue by berkus** [pepyatka/pepyatka-server#101]
Backend tasks to implement server support for User password reminders:
- Extend User to include email field
- Create and validate User's email
- Cover with tests in User model and UsersController

**Comment by berkus** [comment]
I take that one.

**Comment by epicmonkey** [comment]
I've just realised that description is missing a crucial part -- password reminder. To finalise this story we need:
* new controller PasswordsController with two actions PasswordsController#update and PasswordsController#create
* new router PasswordsRoute and two routes
* POST route "/password_resets" to generate resetPasswordToken for a requested email
* PUT route "/password_resets/:resetPasswordToken" to reset password
* in its turn we need to add two extra fields to User model: resetPasswordToken and resetPasswordSentAt
* it makes sense to add few more helper methods to User model: User.prototype.resetPassword(newPassword, newPasswordConfirmation), User.prototype.resetPasswordPeriodValid
* ultimately, please consider indexing resetPasswordToken (i.e. adding a new key to db schema like "reset:<resetTokenId>" with value userId) so you can retrieve user having just a token.

**Comment by berkus** [comment]
Reopen this ticket.

**Comment by epicmonkey** [comment]
Misclicked on "Comment and close" :-)

**Comment by epicmonkey** [comment]
Core functionality is implemented in #140

**Comment by epicmonkey** [comment]
Completed in https://github.com/pepyatka/pepyatka-server/pull/146, https://github.com/pepyatka/pepyatka-server/pull/145, https://github.com/pepyatka/pepyatka-server/pull/143.
