### ISSUE TITLE
Migrate Attachment model

### ISSUE THREAD

**Issue by epicmonkey** [pepyatka/pepyatka-server#102]
Migration Attachment model from master to develop branch.

**Comment by clbn** [comment]
Partially implemented in https://github.com/pepyatka/pepyatka-server/pull/116 (backend) and https://github.com/pepyatka/pepyatka-html/pull/61 (frontend).

**Comment by epicmonkey** [comment]
This is done after https://github.com/pepyatka/pepyatka-server/pull/165
