### ISSUE TITLE
Extract visibility attribute to property

### ISSUE THREAD

**Issue by epicmonkey** [pepyatka/pepyatka-server#126]
Extract visibility attribute to defineProperty from ```GroupsController.js``` to ```Group.js``` model. This will allow us to remove that code from the controller:
```
if (req.body.group.hasOwnProperty('visibility')) {
  newGroup.visibility = req.body.group.visibility
```

**Comment by yole** [comment]
Resolved in 43519a13383ee2e24c1ae3f0e26a718ce2a94bb4

**Comment by epicmonkey** [comment]
Is it? GroupsController still uses code:
```
if (req.body.group.hasOwnProperty('isPrivate')) {
  newGroup.isPrivate = req.body.group.isPrivate
}
```

If we define property in Group model like this we can set all attributes in the controller in the same hash.

Group model:
```
Object.defineProperty(Group.prototype, 'isPrivate', {
  get: function() { return this.isPrivate_ },
  set: function(newValue) {
  if (newValue)
    this.isPrivate_ = newValue || '0'
  }
})
```

GroupsController:
```
var newGroup = new Group({
  username: req.body.group.username,
  screenName: req.body.group.screenName,
  isPrivate: req.body.group.isPrivate
})
```
```

**Comment by yole** [comment]
There is no need to add this code to Group because it's inherited from User. GroupsController can indeed be simplified, you're right.

**Comment by epicmonkey** [comment]
Ha! I knew I was missing something here -- User model indeed!

**Comment by epicmonkey** [comment]
Another spot to simplify: https://github.com/pepyatka/pepyatka-server/blob/development/app/models/group.js#L25
