### ISSUE TITLE
Do not allow to like or un-like post more than one time

### ISSUE THREAD

**Issue by innin** [pepyatka/pepyatka-server#152]
There's no check in `Post.prototype.addLike` and `Post.prototype.removeLike` that this post was already liked or un-liked by this user. This leads to unnecessary notifications sent to subscribers and to endless increment or decrement of likes count (it can even get to negative value).

**Comment by smallq-git** [comment]
Usecase from pepyatka-html/issues/117 should be verified when closing this issue.
