### ISSUE TITLE
User should stay on the same page after subscription

### ISSUE THREAD

**Issue by klera** [pepyatka/pepyatka-server#154]
When user subscribes to a feed - he should stay on the same page after subscription. (and choose lists for the feed he subscribed to, later)

Now after subscription user is redirected to an empty page.

**Comment by epicmonkey** [comment]
Please move this ticket to pepyatka-html project. Any questions what is the difference between pepyatka-server and pepyatka-html let me know.

**Comment by klera** [comment]
Done, https://github.com/pepyatka/pepyatka-html/issues/159

**Comment by epicmonkey** [comment]
Thank you. :sunflower:
