### ISSUE TITLE
User stays on sign in page after second login attempt

### ISSUE THREAD

**Issue by ptzn** [pepyatka/pepyatka-server#157]
1. Go to Sign In page https://micropeppa.freefeed.net/#/session/signin
2. Enter invalid login/password
3. Press "sign in" -> see an error
4. Enter valid login/password and press "sign in" again

Expected: user should be redirected to the personal/home page
Actual: user logged in (right sidebar is updated) but stays on the Sign In page

![screenshot 2015-04-18 14 03 35](https://cloud.githubusercontent.com/assets/12827/7215177/5d2def68-e5d3-11e4-8dcd-c6f3f696761d.png)

**Comment by epicmonkey** [comment]
@ptzn can you please create a ticket in pepyatka-html project? This is a frontend issue.

**Comment by ptzn** [comment]
Done.
