### ISSUE TITLE
Un-liked post doesn't disappear from the likes list.

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-server#166]
1. Log in.
2. Like a post.
3. Go to likes section (https://micropeppa.freefeed.net/#/newuser1/likes)
4. Un-like the post -> user's name disappears from the list of likers.

Expected: post disappears from the list of likes.
Actual: post remains in the list of liked posts.

![image](https://cloud.githubusercontent.com/assets/7983303/7229360/6b43082e-e76b-11e4-882f-4fcecee7ee39.png)

**Comment by smallq-git** [comment]
Possibly related to https://github.com/pepyatka/pepyatka-server/issues/152

**Comment by epicmonkey** [comment]
This is a backend story. Though keeping this one to get everyone in sync.

**Comment by epicmonkey** [comment]
Shoots. This is backend already. Disregard my last comment. Sorry.

**Comment by epicmonkey** [comment]
Created separate story: https://github.com/pepyatka/pepyatka-server/issues/170

**Comment by smallq-git** [comment]
Looks like it's still here:

![image](https://cloud.githubusercontent.com/assets/7983303/7286510/2d24d4b4-e955-11e4-8bb7-8102e91e33d4.png)

**Comment by epicmonkey** [comment]
I wonder did you refresh the page after you un-liked the post?

**Comment by smallq-git** [comment]
@epicmonkey Refreshed, left for other pages, logged out and back in again.

**Comment by smallq-git** [comment]
Can't reproduce anymore. Closing.
