### ISSUE TITLE
Need validation for new group form

### ISSUE THREAD

**Issue by ptzn** [pepyatka/pepyatka-server#167]
1. Go to the https://micropeppa.freefeed.net/#/groups/new
2. Leave one or all inputs empty
3. Press the "Create Feed" button

Expected: error in human readable format.
Actual: "Error: Cannot read property 'length' of undefined" error message

![screenshot 2015-04-20 19 45 01](https://cloud.githubusercontent.com/assets/12827/7235209/52705cd2-e795-11e4-93ad-124eb597f222.png)

**Comment by epicmonkey** [comment]
Hides programmatic errors and replaces "Error: Cannot read property 'length' of undefined" to more generic "Invalid". Though error handling could be improved even more

**Comment by smallq-git** [comment]
better messaging on this page: https://github.com/pepyatka/pepyatka-html/issues/272
