### ISSUE TITLE
Wrong number of subscriptions is displayed in user profile

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-server#173]
For some users number of subscriptions is displayed incorrectly.

For example, arefiev has 7 subscriptions counted in profile:
![image](https://cloud.githubusercontent.com/assets/7983303/7287378/ac1afd00-e95c-11e4-9993-5c81a7f1250d.png)

But only 4 subscriptions are listed:
![image](https://cloud.githubusercontent.com/assets/7983303/7287381/b4aea3cc-e95c-11e4-964e-94f9ea1bd087.png)

**Comment by innin** [comment]
Validation similar to solution for #152 might work here. Check if user is already subscribed when he subscribes or unsubscribes to prevent multiple subscribe/unsubscribe calls
