### ISSUE TITLE
Server didn't discards duplicates then counting users.statistics.subscribers

### ISSUE THREAD

**Issue by iAdramelk** [pepyatka/pepyatka-server#184]
How to reproduce:

1. Go to user/group page.
2. Click Subscribe.
3. Click back in browser.
4. Click subscribe again.
5. Repeat steps 3-4 few more times.

Result: Subscribers counter shows number of clicks. (All clicks was counted towards users.statistics.subscribers, but subscribers list shows user only once)

Expected behavior: users.statistics.subscribers only updates once.

**Comment by epicmonkey** [comment]
Dup of https://github.com/pepyatka/pepyatka-server/issues/173. If it covers any other cases let me know.
