### ISSUE TITLE
Serve returns blank 422 response then you post comment without text

### ISSUE THREAD

**Issue by iAdramelk** [pepyatka/pepyatka-server#185]
How to reproduce:

1. Click Comment.
2. Click post without entering text.

Actual: Nothing happens but server returns blank 422 response without error description.

Expected: Server returns 422 response with error description.

P. S. When you try to post blank comment then editing, server returns {err: "invalid"}

**Comment by epicmonkey** [comment]
I'm going to close this one if favour a bigger story that describes a lot of cases to cover both on frontend and backend sides: https://github.com/pepyatka/pepyatka-html/issues/271
