### ISSUE TITLE
Can subscribe to a group twice right after creation

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-server#188]
1. Log in.
2. Go to Create group page.
3. Create a group.

Expected: Subscribe link is not displayed if you're already subscribed to the group.
Actual: Subscribe link is displayed for the newly created group and creator can subscribe to their own group (which results in https://github.com/pepyatka/pepyatka-server/issues/173)

**Comment by epicmonkey** [comment]
@smallq-git Excuse me, can you move this ticket to pepyatka-html project please?

**Comment by smallq-git** [comment]
:facepalm: that'll teach me to use links from any open tab.
https://github.com/pepyatka/pepyatka-html/issues/298 created. closing this one.
