### ISSUE TITLE
User created via server API will not have email recognized by the system until settings are updated

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-server#197]
MIgrated user cannot request a password reset because their email is not associated with their account - Record Not Found error is displayed.

Pre-condition: Have a user validated on about.freefeed.net
1. Migrate user via /status.
2. Verify that user settings contain email.
3. Log out.
4. Enter incorrect password on Sign in page.
5. Follow the Forgot password link.
6. Enter email associated with the account.

Expected: reset password email is sent.
Actual: Error is displayed:
![image](https://cloud.githubusercontent.com/assets/7983303/7447322/f2a34aca-f1fe-11e4-8c04-11692e068d3b.png)

**Comment by berkus** [comment]
When you login successfully and press Update in the user email section of settings, the email is applied correctly and can be used to reset afterwards.

Must be some problem with populating denormalised user data in UserController or User model ctor.

**Comment by epicmonkey** [comment]
@berkus Can you move this story to freefeed repository?

**Comment by berkus** [comment]
This is not freefeed-specific. Some problem with user account creation.
