### ISSUE TITLE
Jpeg "lossless" rotation is not preserved

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-server#199]
When a jpeg picture with portrait orientation is attached, thumbnail is always displayed in landscape. Original picture remains in portrait when opened.

**Comment by berkus** [comment]
Server-side resizer should be fixed to strip EXIF info and rotate the picture into correct orientation itself.

**Comment by smallq-git** [comment]
Verified:
![Uploading image.png…]()
