### ISSUE TITLE
MyDiscussions: list of likes is not sorted

### ISSUE THREAD

**Issue by indeyets** [pepyatka/pepyatka-server#224]
Like of currently logged-in user is returned on the first position, since recently. With a single omission: "My Discussions" timeline.

@epicmonkey suggested, that the fix should be the replacement of code on line:  https://github.com/pepyatka/pepyatka-server/blob/7116180136eb9fbc94fcf8b4f8f3ff17a268e012/app/models/user.js#L366

`models.Timeline.findById(that.id)` should be replaced by `models.Timeline.findById(that.id, params)`

**Comment by smallq-git** [comment]
Fixed:
![image](https://cloud.githubusercontent.com/assets/7983303/7995569/df900cc2-0b1f-11e5-8c6a-6cbe1c60abf3.png)
