### ISSUE TITLE
Server shouldn't die if Redis is not available

### ISSUE THREAD

**Issue by indeyets** [pepyatka/pepyatka-server#225]
Right now, server dies as soon as connection to redis is broken. It would be nice to implement a more friendly solution.

Proposal:
1. try to reconnect (while keeping clients on hold) for several iterations with increasing sleeps (100ms, 500ms, 5s)
2. send "db is not available" errors to clients
3. keep connection retries once every 5s (and send errors to all queued clients on this 5s borders)

**Comment by epicmonkey** [comment]
Resolved in https://github.com/pepyatka/pepyatka-server/commit/d83fab6ed094504ea63f1e6c4685fba52828e43e
