### ISSUE TITLE
User can create group with non-latin username

### ISSUE THREAD

**Issue by davidmz** [pepyatka/pepyatka-server#226]
Example: https://micropeppa.freefeed.net/микрогруппа

**Comment by epicmonkey** [comment]
Same for usernames. I agree only latin and underscore are allowed (pretty much the same as in Twitter).

**Comment by davidmz** [comment]
I remembered that in old FrF hyphen (-) was permitted too (in groupname 'save-our-snobs', for example).

**Comment by epicmonkey** [comment]
Good catch! I guess group could start with an underscore, however not with a hyphen?

**Comment by davidmz** [comment]
There are no usernames/groupnames with underscore in my personal FrF backup (my friends and some other users/groups). Moreover, there is no single USERnames with hyphens, hyphens are present only in groupnames. Maybe we should check the Clio archives?

**Comment by smallq-git** [comment]
"-" replaced any spaces entered in username. No special characters were permitted.

**Comment by epicmonkey** [comment]
Tests:
```
Group
 #isValidUsername ()
  ✓ should allow username luna
  ✓ should allow username 12345
  ✓ should allow username hello1234
  ✓ should allow username save-our-snobs
  ✓ should not allow invalid username lu
  ✓ should not allow invalid username -12345
  ✓ should not allow invalid username luna-
  ✓ should not allow invalid username hel--lo
  ✓ should not allow invalid username абизьян

User
 #isValidUsername ()
  ✓ should allow username luna (93ms)
  ✓ should allow username 12345 (84ms)
  ✓ should allow username hello1234 (79ms)
  ✓ should not allow invalid username lu
  ✓ should not allow invalid username -12345
  ✓ should not allow invalid username luna-
  ✓ should not allow invalid username hel--lo
  ✓ should not allow invalid username save-our-snobs
  ✓ should not allow invalid username абизьян
```

**Comment by smallq-git** [comment]
Group name autogeneration: https://github.com/pepyatka/pepyatka-html/issues/448
