### ISSUE TITLE
User can't create group: error 422

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-server#237]
Initially I was having this issue: https://github.com/pepyatka/pepyatka-server/issues/234. But now the same user cannot use the workaround either: when I enter Screen Name and Username and click Create Group button, I get error message "Error: Invalid" and 422 error in console.

![image](https://cloud.githubusercontent.com/assets/7983303/8045871/4b7214fe-0e3f-11e5-8be8-bb94402f704c.png)

POST https://micropeppa.freefeed.net/v1/groups 422 (Unprocessable Entity)jQuery.ajaxTransport.send @ config.js?v=f19a9a0eb233d49a0877e46c0968c39d9c936fc6:8716jQuery.extend.ajax @ config.js?v=f19a9a0eb233d49a0877e46c0968c39d9c936fc6:8252a.extend.ajax @ config.js?v=f19a9a0eb233d49a0877e46c0968c39d9c936fc6:56612initializePromise @ config.js?v=f19a9a0eb233d49a0877e46c0968c39d9c936fc6:54218Promise @ config.js?v=f19a9a0eb233d49a0877e46c0968c39d9c936fc6:55846a.extend.ajax @ config.js?v=f19a9a0eb233d49a0877e46c0968c39d9c936fc6:56612a.extend.createRecord @ config.js?v=f19a9a0eb233d49a0877e46c0968c39d9c936fc6:56612Pt @ config.js?v=f19a9a0eb233d49a0877e46c0968c39d9c936fc6:56614(anonymous function) @ config.js?v=f19a9a0eb233d49a0877e46c0968c39d9c936fc6:56614forEach @ config.js?v=f19a9a0eb233d49a0877e46c0968c39d9c936fc6:20658zt.extend.flushPendingSave @ config.js?v=f19a9a0eb233d49a0877e46c0968c39d9c936fc6:56614Queue.invoke @ config.js?v=f19a9a0eb233d49a0877e46c0968c39d9c936fc6:10168Queue.flush @ config.js?v=f19a9a0eb233d49a0877e46c0968c39d9c936fc6:10233DeferredActionQueues.flush @ config.js?v=f19a9a0eb233d49a0877e46c0968c39d9c936fc6:10038Backburner.end @ config.js?v=f19a9a0eb233d49a0877e46c0968c39d9c936fc6:9463Backburner.run @ config.js?v=f19a9a0eb233d49a0877e46c0968c39d9c936fc6:9518run @ config.js?v=f19a9a0eb233d49a0877e46c0968c39d9c936fc6:24754handleRegisteredAction @ config.js?v=f19a9a0eb233d49a0877e46c0968c39d9c936fc6:27193(anonymous function) @ config.js?v=f19a9a0eb233d49a0877e46c0968c39d9c936fc6:45445jQuery.event.dispatch @ config.js?v=f19a9a0eb233d49a0877e46c0968c39d9c936fc6:4521jQuery.event.add.elemData.handle @ config.js?v=f19a9a0eb233d49a0877e46c0968c39d9c936fc6:4207

**Comment by epicmonkey** [comment]
Screen name must be between 3 and 25.

**Comment by smallq-git** [comment]
We really need better error messages. like, REALLY.

**Comment by epicmonkey** [comment]
It's in the roadmap. Sigh :-(
