### ISSUE TITLE
review post deletion

### ISSUE THREAD

**Issue by epicmonkey** [pepyatka/pepyatka-server#238]
dragons!

**Comment by epicmonkey** [comment]
Fixed symptoms in https://github.com/pepyatka/pepyatka-server/commit/f9bce6412774fa21603711af4d3b88aa15ac0e27

**Comment by berkus** [comment]
> у @SiTLar в какой-то момент образовалась битая база, я починил симптом, но не уверен, что починил проблему. в таймлайн пользователя попадал как-то пост, который был удалён.

**Comment by epicmonkey** [comment]
Moving to 0.2.2

**Comment by epicmonkey** [comment]
Lowering to 0.4.0

**Comment by epicmonkey** [comment]
in fact, noone is going to review this. closing.
