### ISSUE TITLE
'/v1/users/:username/subscriptions' API call doesn't respond

### ISSUE THREAD

**Issue by davidmz** [pepyatka/pepyatka-server#241]
Example: https://freefeed.net/v1/users/davidmz/subscriptions

**Comment by berkus** [comment]
Reproducible on micropeppa as well.

**Comment by berkus** [comment]
[ ] filter empty records in output
[ ] in User.prototype.updateLastActivityAt instead of that.id use timelineId

**Comment by epicmonkey** [comment]
Copy this script to ./bin/ and run it: https://gist.github.com/epicmonkey/37e10cff049b290d1d7c
