### ISSUE TITLE
Moderation: User should be able to delete any comments on her own threads

### ISSUE THREAD

**Issue by urbansheep** [pepyatka/pepyatka-server#250]
User should be able to delete any comments on her own threads, both in her feed and in any groups or direct messages.

Deletion mode is triggered by turning on the «Moderate comments» option in the post actions menu, and this adds “Delete” option for all of the comments in the thread (not just user's own comments).

After comment is deleted, it is replaced with a message “Comment deleted”, with an option “Undo?” to revert deletion.

When page is reloaded, deleted posts don't appear anymore, and undo is not possible.

**Comment by berkus** [comment]
This should probably be in -html

**Comment by urbansheep** [comment]
Thanks, will move.
