### ISSUE TITLE
[Verified] Direct: filter foaf for direct messages on like

### ISSUE THREAD

**Issue by epicmonkey** [pepyatka/pepyatka-server#261]
Preconditions:
- user A, user B, and user C are created
- user A subscribed to user B, and user C
- user B is subscribed to user A, and user C
- user C is subscribed to user A, and user B

Steps:
1) user A sends a direct message to user B
2) user A likes that post

Expected result:
- Direct message is not visible for user C in home feed

Actual result:
- Direct message is in user C home feed
- Note: that user C cannot view that post by direct link, only in home feed

**Comment by smallq-git** [comment]
Doesn't happen anymore for 3rd party in homefeed or individual feed of either of direct participants
