### ISSUE TITLE
[Verified] Post shouldn't be shown as "private" if posted to public feed

### ISSUE THREAD

**Issue by indeyets** [pepyatka/pepyatka-server#276]
Currently, a post by a user which is sent to user's own private feed and a public group is shown as "private" even if everyone sees it in a group without requesting any permissions from user.

Should be shown as public instead. See https://micropeppa.freefeed.net/music/915845c9-aa3c-4e7c-81e5-059fd164a6fe

**Comment by epicmonkey** [comment]
In fact, this is html issue. Tho' don't worry, will fix in either way.

**Comment by epicmonkey** [comment]
resolved in https://github.com/pepyatka/pepyatka-html/commit/4f1e9db676cd58a3a649d9fc2358b74106a95ea7

**Comment by smallq-git** [comment]
Fixed: https://micropeppa.freefeed.net/cheese/a031dddc-6282-4278-b438-ed5bc9b0c891
![image](https://cloud.githubusercontent.com/assets/7983303/9238900/f4239b7a-415e-11e5-9c4b-e7fad658d300.png)
