### ISSUE TITLE
Privates: Strange 422 reply when trying to request subscription

### ISSUE THREAD

**Issue by payalnik** [pepyatka/pepyatka-server#280]
https://www.dropbox.com/s/dbc21o8ybgjb3jl/Screenshot%202015-08-04%2013.55.37.png?dl=0

**Comment by epicmonkey** [comment]
I think I got it. Most likely you've already requested a subscription to this feed. I'll make it more clear.

**Comment by epicmonkey** [comment]
This commit hides Request subscription link if there is a pending request. https://github.com/pepyatka/pepyatka-html/commit/a65e72c549265d96da289956e594f581346158fc
