### ISSUE TITLE
Multiprocessing and Node cluster

### ISSUE THREAD

**Issue by indeyets** [pepyatka/pepyatka-server#42]
Server should be able to start several processes to be able to fully utilize several CPU cores.

The official way of doing this is http://nodejs.org/api/cluster.html

(originally proposed in #40)

**Comment by epicmonkey** [comment]
This is done using pm2 now. We need to document this in wiki.

**Comment by id** [comment]
PM2 does not play nice with socket.io: https://github.com/Unitech/PM2/issues/637

Need another solution.

**Comment by id** [comment]
Resolved in deploy script: https://github.com/pepyatka/pepyatka-ansible/pull/37

**Comment by epicmonkey** [comment]
Shall we close it then?
