### ISSUE TITLE
Provide endpoints to obtain full list of likes

### ISSUE THREAD

**Issue by epicmonkey** [pepyatka/pepyatka-server#73]
- Return limited list of likes by default from server with indication how many more likes are missing
- Provide endpoints to obtain full list of likes

**Comment by denspb** [comment]
Note, that if currently signed-in user liked the post, "You" should be first of those 3 links.

**Comment by berkus** [comment]
This is ticket for `pepyatka-html`

**Comment by epicmonkey** [comment]
Not quite. In the perfect conditions server will return just a limited set of likes to a client and so client will need an end-point to get a full list.

**Comment by epicmonkey** [comment]
But. Lowering priority.

**Comment by berkus** [comment]
Ok, so this should be rephrased as:
```
- Provide endpoints to obtain full list of likes
- Return limited list of likes by default from server with indication how many more likes are missing
```

**Comment by epicmonkey** [comment]
Agree.

**Comment by clbn** [comment]
Well, we might not need a separate endpoint, it could be just the 'get one post' endpoint we have.

**Comment by epicmonkey** [comment]
Get one post will return a little more redundant content like comments. I'd prefer having another route for likes only.

**Comment by clbn** [comment]
Or, it says 'likes', not 'comments'. My mistake. Do we need the same for comment list?

**Comment by epicmonkey** [comment]
Indeed! It's already there: https://github.com/pepyatka/pepyatka-server/issues/67 (and I've just lowered priority for this one as well)

**Comment by epicmonkey** [comment]
I'm reopening this issue to return You in the limited list of likes.

**Comment by epicmonkey** [comment]
Resolved in https://github.com/pepyatka/pepyatka-server/commit/eb3809c. Though currentUser is still shown as screenName she is in the first position now.
