### ISSUE TITLE
Authorize users prior subscribing them to feed/post

### ISSUE THREAD

**Issue by epicmonkey** [pepyatka/pepyatka-server#76]
Right now this is not a security issue as we do not have any private feeds, however in the future we must be doing authorization on "subscribe" event:
- authorized user is a user who is in the list of subscribed users
- public feed bypasses authorization.

Otherwise user can subscribe to any feed and receive new posts and comments in real-time even she does not have an access to that feed.

**Comment by epicmonkey** [comment]
Connected to https://github.com/pepyatka/pepyatka-server/issues/112

**Comment by berkus** [comment]
Means we gotta do it now?

**Comment by epicmonkey** [comment]
Resolved in 77e30f051a14647167ae7920704620dcf4e66487
